In [2]:
!nvidia-smi #to check gpu

Invalid combination of input arguments. Please run 'nvidia-smi -h' for help.



In [3]:
#import tensorflow
import tensorflow as tf
tf.__version__  #tensorflow version

'2.17.0'

In [4]:
#creating tensor  tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#ndim no of dimension
scalar.ndim

0

In [6]:
# vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
matrix.ndim

2

In [10]:
another_matrix= tf.constant([[10.,7.],[3.,2.],[8.,9.]] ,dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

**dot (.) after an integer is called 32 bit precison means<br>
after decimal single value is stored like 6.0 ,7.0**

In [11]:
another_matrix.ndim

2

In [12]:
another_matrix.shape

TensorShape([3, 2])

In [13]:
## create a tensor

In [14]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [15]:
tensor.ndim

3

**so what i learn so far<br>**
**scalar - 0 dimension single number<br>
vector - a list of no. (no with direction example speed wind etc)<br>
matrix - 2 dimensional no of arrays<br>
tensor - n dimensional array where n can be any no.<br>**


In [19]:
# create tensor with tf.Variable

# capital v in tf.Variable

changeable_tensor=tf.Variable([10,7])
changeable_tensor
unchangeable_tensor=tf.constant([10,7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [20]:
#now try to change or i say try to assign value


changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
# ok = not supported what should we do

In [22]:
# we have to use .assign() 

changeable_tensor=changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [23]:
# we cant change in constant variable

# it is done becz we dont want  in tensors that our values will change

In [24]:
# if you ever in doubt what u should use generally use tf.constant and after that u can change into tf.Variable wheneveru want

#### **creating random tensors**

In [25]:
# fill tensor with random numbers
# tf.random.Generator ---->to generate random no
# G in generator is capital
# .from_seed(seednumber)  ----> to produce reproducibility so hat when someone need the exac same no that  i hav created randomly they should also get the same numbers

random1 = tf.random.Generator.from_seed(7)

print(random1) # object is generated
#using normal distribution and giving shape as a parameter to form a matrix
# tf.random.uniform(shape=(rows,columns))
#u can also use uniform in place of normalisation
random1=tf.random.normal(shape=(3,3))
random1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.574194  , -1.2693232 ,  0.54793024],
       [-1.2630643 ,  0.11524454,  0.512943  ],
       [ 0.74486023, -0.3288183 ,  0.11179338]], dtype=float32)>

In [26]:
#now create random2
random2 = tf.random.Generator.from_seed(7)
print(random2)
random2 = tf.random.uniform(shape=(3,3))
random2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.57543457, 0.9251652 , 0.38107085],
       [0.57366335, 0.05668557, 0.36474216],
       [0.02954078, 0.4860227 , 0.11506069]], dtype=float32)>

In [27]:
# is random1 thatuses normal distribution and random2 that uses uniform distribution are they same?
# lets check it out


random1==random2

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False],
       [False, False, False]])>

In [28]:
# can we shuffle our tensors lets See

#tf.random.shuffle is used to shuffle

random1= tf.constant([[1,2],[3,4],[5,6]])
print(random1)

# now doing the shuffling

print("\n\nafter shuffling")

random1=tf.random.shuffle(random1)
print(random1)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


after shuffling
tf.Tensor(
[[5 6]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)


In [29]:
# to do random shuffling in an order so every time it shufffle in this order we Use

# tf.random.set_sed(seednumber)

# and afterthatintf.random.shuffle()
# we passs a parameter in this function seed=seednumber


print("\n\nafter shuffling")
tf.random.set_seed(42)
random1=tf.random.shuffle(random1, seed=42)
print(random1)



after shuffling
tf.Tensor(
[[5 6]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)


**seed are of 2 types<br>
1.global level seeds <br>
2.operational level seeds<br><br>
the tf.random.set_seed(seednumber)---->this is our global seed<br>
and the parameter seed=seednumber is our operational level seed<br>**

In [30]:
#doc string appears  in colab shift+ctrl+space
# you can remeber this as it formed aplhabet letter L in keyboard

**1.If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.<br><br>
2.If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.<br><br>
3.If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.<br><br>
4.If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.<br>**

****other ways to make tensors you should know****

In [31]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [32]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [33]:
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [34]:
tf.zeros(shape=[3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

#### **converting numpy arrays into tensors**

In [35]:
# converting numpy arrays into tensors

# difference b/w numpy arrays and tensors is simple
# tensors can run on gpu whereas numpy cannot

# creating a numpy array
import numpy as np # importing numpy 
numpy_array=np.arange(1,25,dtype=np.int32)
numpy_array

# np.arange is used to give a range
# pass range in parameters
# np.arange(starting, ending_is_exclusive, dtype=np.float16/np.int32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [36]:
#converting into tensor 

tensor= tf.constant(numpy_array)
tensor

# we can change its shape to form a tensor of any dimension
tensor=tf.constant(numpy_array,shape=(6,4))
tensor

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [37]:
# information from tensor

#   terms                                meaning                 code
#   in language

#   shape                      length of no of elements        tensor.shape



#   ndim or also called rank      scalar has 0 ndim            tensor.ndim
#                                 vector has 1 ndim
#                                 matrix has 2 ndim



#   size                            total no of item           tf.size(tensor)




#   access an                       tensor row accessing        tensor[0]
#   axis 




In [38]:
# and a one more to find datatype of tensor

# tensor.dtype

In [39]:
# creating a tensor
# four_dim_tensor or can say rank 4 tensor 


four_dim_tensor=tf.ones(shape=(2,3,4,5),dtype=tf.int32)
# here 2- means 2 group
# 3-means each group has 3 members
# 4-means each member has 4 rows
# 5-means each member has 5 column
four_dim_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])>

In [40]:
# what is the shape?
four_dim_tensor.shape

TensorShape([2, 3, 4, 5])

In [41]:
# what is  ndim of four_dim_tensor?

four_dim_tensor.ndim

4

In [42]:
# how much  is tensor all elements?
tf.size(four_dim_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [43]:
### this tf.size output is not satisfying lets make it better
# so that we can view it better

#by using dot (.)numpy()

tf.size(four_dim_tensor).numpy()

120

In [44]:
# viewing the shape


# first defining.shape[index]

four_dim_tensor.shape[0]

# 0 index par kon si shape h



2

In [45]:
# viewing the shape


# first defining.shape[index]

four_dim_tensor.shape[-1]

# last index par kon si shape h


5

In [46]:
# what is the datatype of this four_dim_tensor?
four_dim_tensor.dtype

tf.int32

In [47]:
# supppose we have some list how canweaccess its elements

some_list = [1,2,3,4,5]

# access first element
some_list[0]

1

In [48]:
# supposewe have a matrix of shape 2,3,2

matrix=tf.constant([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print (matrix)

tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]], shape=(2, 3, 2), dtype=int32)


In [49]:
##aceesing first row of each 

matrix[:,:,1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [50]:
# accessing first element of each
matrix[0:2,0:1,0:1]

<tf.Tensor: shape=(2, 1, 1), dtype=int32, numpy=
array([[[1]],

       [[7]]])>

In [51]:
another_matrix=tf.ones(shape=(2,2))
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [52]:
#expanding the dimension 
# supppose we want to expand dimension lets suppose at last 
another_matrix_dim3=another_matrix[:,:, tf.newaxis]
another_matrix_dim3

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [53]:
#expanding the dimension 
# supppose we want to expand dimension lets suppose at last 
another_matrix_dim3=another_matrix[..., tf.newaxis]
another_matrix_dim3

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [54]:
another_matrix_dim3=tf.expand_dims(another_matrix,axis=-1)
another_matrix_dim3
#axis=?   value 0 means index 0 ,value1 means index 1 value -1 means index last

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

#### **tensor basic operations like + - * /**

In [55]:
#suppose we have a tensor 
tensor1= tf.constant([[10,15],
                      [20,25]])
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 15],
       [20, 25]])>

In [56]:
tensor1+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 25],
       [30, 35]])>

In [57]:
tensor1-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0,  5],
       [10, 15]])>

In [58]:
tensor1*10  # multiply to each individual element

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 150],
       [200, 250]])>

In [59]:
tensor1/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 1.5],
       [2. , 2.5]])>

In [60]:
#you can use built in function 
#which generally are built for process faster by gpu


# tf.math.add(tensor_name,value_you_want_to_add)

# aise hi tf.math.multiply(tensor_name,value_you_want_to_add) hai multiply to each individual element

In [61]:
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 15],
       [20, 25]])>

In [62]:
#lets give it a try with multiply to each individual element using built in

tf.math.multiply(tensor1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 150],
       [200, 250]])>

In [63]:
# we can use like this without .math 
tf.multiply(tensor1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 150],
       [200, 250]])>

#### **matrix multiply real**

In [64]:
tf.matmul(tensor1,tensor1) #here matrix multiply real matrix occurs here

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 525],
       [700, 925]])>

In [65]:
# we can use python operator @ for actual matrix multiplication
tensor1 @ tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 525],
       [700, 925]])>

#### **visualize through this website http://matrixmultiplication.xyz**

In [66]:
import tensorflow as tf
tensor1= tf.constant([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
tensor1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [67]:
tensor2= tf.constant([[1,2],
                     [4,5],
                     [7,8]])
tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]])>

In [68]:
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 30,  36],
       [ 66,  81],
       [102, 126]])>

**2 rules of matrix multiplication real wali<br><br>
1.inner dimension must match<br>
2.outer dimension is the result**

In [69]:
#suppose we have a matrix 
tensor1= tf.constant([[1,2,3],
                     [4,5,6],
                     ])
tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [70]:
# reshaping this matrix 
tf.reshape(tensor1,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [72]:
#what istranspose
x=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
            ])

x.shape

TensorShape([3, 3])

**transpose -------flip axes**

In [73]:
tf.transpose(x)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])>

In [81]:
print(x)

y=tf.constant([
            [1,2,3],
            [4,5,6],
            
            ])
print(y)
y.shape

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


TensorShape([2, 3])

***multiply using another method tf.tensordot()**

In [82]:
tf.tensordot(x,tf.transpose(y),axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 14,  32],
       [ 32,  77],
       [ 50, 122]])>

default datatype of matrix is int32 sometimes we need to change it according to our problem how to do it

In [86]:
x=tf.constant([
    [1,2,3],
    [4,5,6],
])
print(x)
print(x.dtype)
y=tf.constant([
    [1.,2.,3.],
    [4.,5.,6.],
    
])

print(y)
print(y.dtype)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
<dtype: 'int32'>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
<dtype: 'float32'>


In [88]:
## changing tensor data types

tf.cast(x,dtype=tf.float16)

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>