In [1]:
!nvidia-smi

Tue Nov 26 02:19:10 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 475.14       Driver Version: 475.14       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 N/A |                  N/A |
| 30%    0C    P8    N/A /  N/A |   1486MiB /  4096MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
#import tensorflow
import tensorflow as tf
tf.__version__

'2.17.0'

In [3]:
#creating tensor  tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#ndim no of dimension
scalar.ndim

0

In [5]:
# vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
another_matrix= tf.constant([[10.,7.],[3.,2.],[8.,9.]] ,dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

#### dot (.) after an integer is called 32 bit precison means
#### after decimal single value is stored like 6.0 ,7.0

In [10]:
another_matrix.ndim

2

In [11]:
another_matrix.shape

TensorShape([3, 2])

In [12]:
## create a tensor

In [13]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [14]:
tensor.ndim

3

**so what i learn so far<br>**
scalar - 0 dimension single number<br>
vector - a list of no. (no with direction example speed wind etc)<br>
matrix - 2 dimensional no of arrays<br>
tensor n dimensional array where n can be any no.<br>


In [15]:
# create tensor with tf.Variable

# capital v in tf.Variable

changeable_tensor=tf.Variable([10,7])
changeable_tensor
unchangeable_tensor=tf.constant([10,7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [16]:
#now try to change or i say try to assign value


changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [17]:
# ok = not supported what should we do

In [18]:
# we have to use .assign() 

changeable_tensor=changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [19]:
# we cant change in constant variable

# it is done becz we dont want  in tensors that our values will change

In [20]:
# if you ever in doubt what u should use generally use tf.constant and after that u can change into tf.Variable wheneveru want

### ****creating random tensors****

In [21]:
# fill tensor with random numbers
# tf.random.Generator ---->to generate random no
# G in generator is capital
# .from_seed(seednumber)  ----> to produce reproducibility so hat when someone need the exac same no that  i hav created randomly they should also get the same numbers

random1 = tf.random.Generator.from_seed(7)

print(random1) # object is generated
#using normal distribution and giving shape as a parameter to form a matrix
# tf.random.uniform(shape=(rows,columns))
#u can also use uniform in place of normalisation
random1=tf.random.normal(shape=(3,3))
random1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-2.0041318 , -0.06447469, -0.04501798],
       [-0.38365963, -0.6034663 , -0.5884492 ],
       [ 0.26062372, -0.59225583,  0.34530312]], dtype=float32)>

In [22]:
#now create random2
random2 = tf.random.Generator.from_seed(7)
print(random2)
random2 = tf.random.uniform(shape=(3,3))
random2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.9717412 , 0.9813802 , 0.61278164],
       [0.49038482, 0.15423882, 0.10112417],
       [0.30056977, 0.87053776, 0.29248202]], dtype=float32)>

In [23]:
# is random1 thatuses normal distribution and random2 that uses uniform distribution are they same?
# lets check it out


random1==random2

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False],
       [False, False, False]])>

In [24]:
# can we shuffle our tensors lets See

#tf.random.shuffle is used to shuffle

random1= tf.constant([[1,2],[3,4],[5,6]])
print(random1)

# now doing the shuffling

print("\n\nafter shuffling")

random1=tf.random.shuffle(random1)
print(random1)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


after shuffling
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [25]:
# to do random shuffling in an order so every time it shufffle in this order we Use

# tf.random.set_sed(seednumber)

# and afterthatintf.random.shuffle()
# we passs a parameter in this function seed=seednumber


print("\n\nafter shuffling")
tf.random.set_seed(42)
random1=tf.random.shuffle(random1, seed=42)
print(random1)



after shuffling
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


****seed are of 2 types<br>
1.global level seeds <br>
2.operational level seeds<br><br>
the tf.random.set_seed(seednumber)---->this is our global seed<br>
and the parameter seed=seednumber is our operational level seed<br>****

In [26]:
#doc string appears  in colab shift+ctrl+space
# you can remeber this as it formed aplhabet letter L in keyboard

*****1.If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.<br><br>
2.If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.<br><br>
3.If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.<br><br>
4.If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.<br>*****

****other ways to make tensors you should know****

In [27]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [28]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [29]:
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [30]:
tf.zeros(shape=[3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

## ****converting numpy arrays into tensors****

In [31]:
# converting numpy arrays into tensors

# difference b/w numpy arrays and tensors is simple
# tensors can run on gpu whereas numpy cannot

# creating a numpy array
import numpy as np # importing numpy 
numpy_array=np.arange(1,25,dtype=np.int32)
numpy_array

# np.arange is used to give a range
# pass range in parameters
# np.arange(starting, ending_is_exclusive, dtype=np.float16/np.int32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [32]:
#converting into tensor 

tensor= tf.constant(numpy_array)
tensor

# we can change its shape to form a tensor of any dimension
tensor=tf.constant(numpy_array,shape=(6,4))
tensor

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [33]:
# information from tensor

#   terms                                meaning                 code
#   in language

#   shape                      length of no of elements        tensor.shape



#   ndim or also called rank      scalar has 0 ndim            tensor.ndim
#                                 vector has 1 ndim
#                                 matrix has 2 ndim



#   size                            total no of item           tf.size(tensor)




#   access an                       tensor row accessing        tensor[0]
#   axis 




In [34]:
# and a one more to find datatype of tensor

# tensor.dtype

In [35]:
# creating a tensor
# four_dim_tensor or can say rank 4 tensor 


four_dim_tensor=tf.ones(shape=(2,3,4,5),dtype=tf.int32)
# here 2- means 2 group
# 3-means each group has 3 members
# 4-means each member has 4 rows
# 5-means each member has 5 column
four_dim_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])>

In [36]:
# what is the shape?
four_dim_tensor.shape

TensorShape([2, 3, 4, 5])

In [40]:
# what is  ndim of four_dim_tensor?

four_dim_tensor.ndim

4

In [37]:
# how much  is tensor all elements?
tf.size(four_dim_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [38]:
### this tf.size output is not satisfying lets make it better
# so that we can view it better

#by using dot (.)numpy()

tf.size(four_dim_tensor).numpy()

120

In [45]:
# viewing the shape


# first defining.shape[index]

four_dim_tensor.shape[0]

# 0 index par kon si shape h



2

In [47]:
# viewing the shape


# first defining.shape[index]

four_dim_tensor.shape[-1]

# last index par kon si shape h


5

In [39]:
# what is the datatype of this four_dim_tensor?
four_dim_tensor.dtype

tf.int32