In [2]:
!nvidia-smi

Mon Nov 25 21:35:34 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 475.14       Driver Version: 475.14       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 N/A |                  N/A |
| 30%    0C    P8    N/A /  N/A |   1449MiB /  4096MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
#import tensorflow
import tensorflow as tf
tf.__version__

'2.17.0'

In [4]:
#creating tensor  tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#ndim no of dimension
scalar.ndim

0

In [6]:
# vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
matrix.ndim

2

In [16]:
another_matrix= tf.constant([[10.,7.],[3.,2.],[8.,9.]] ,dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

#### dot (.) after an integer is called 32 bit precison means
#### after decimal single value is stored like 6.0 ,7.0

In [17]:
another_matrix.ndim

2

In [18]:
another_matrix.shape

TensorShape([3, 2])

In [19]:
## create a tensor

In [25]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [26]:
tensor.ndim

3

**so what i learn so far<br>**
scalar - 0 dimension single number<br>
vector - a list of no. (no with direction example speed wind etc)<br>
matrix - 2 dimensional no of arrays<br>
tensor n dimensional array where n can be any no.<br>


In [ ]:
# create tensor with tf.Variable

# capital v in tf.Variable

changeable_tensor=tf.Variable([10,7])
changeable_tensor
unchangeable_tensor=tf.constant([10,7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [9]:
#now try to change or i say try to assign value


changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [10]:
# ok = not supported what should we do

In [12]:
# we have to use .assign() 

changeable_tensor=changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [13]:
# we cant change in constant variable

# it is done becz we dont want  in tensors that our values will change

In [14]:
# if you ever in doubt what u should use generally use tf.constant and after that u can change into tf.Variable wheneveru want

### ****creating random tensors****

In [ ]:
# fill tensor with random numbers
# tf.random.Generator ---->to generate random no
# G in generator is capital
# .from_seed(seednumber)  ----> to produce reproducibility so hat when someone need the exac same no that  i hav created randomly they should also get the same numbers

random1 = tf.random.Generator.from_seed(7)

print(random1) # object is generated
#using normalisation and giving shape as a parameter to form a matrix
# tf.random.uniform(shape=(rows,columns))
#u can also use uniform in place of normalisation
random1=tf.random.normal(shape=(3,3))
random1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.9048696 , -0.3505635 , -0.64074355],
       [ 2.2184267 ,  0.49243382, -0.0350071 ],
       [ 0.00843726, -0.7232036 ,  1.0474777 ]], dtype=float32)>

In [ ]:
#now create random2
random2 = tf.random.Generator.from_seed(7)
print(random2)
random2 = tf.random.uniform(shape=(3,3))
random2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.29870367, 0.486861  , 0.65873325],
       [0.7369088 , 0.9802265 , 0.5637748 ],
       [0.47520936, 0.23878014, 0.0027051 ]], dtype=float32)>

In [25]:
# is random1 thatuses normalization and random2 that uses uniform are they same?
# lets check it out


random1==random2

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False],
       [False, False, False]])>

In [ ]:
#doc string appears  shift+ctrl+space